title: Design System
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://designsystem.gov.scot" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #scotgov
github_username: #scottishgovernment
examples_gtm_code: GTM-5S47S9Z
sass:
    sass_dir: assets/_scss
host: 0.0.0.0
# Build settings
markdown: kramdown
plugins:
#  - jekyll-sitemap
#  - jekyll-redirect-from
  - jekyll-admin
collections:
  site-furniture:
    output: true
    permalink: /:name/
    parent: home
maxphase: 2
includeDevNotes: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll_admin:
  hidden_links:
    - posts
    - site-furniture
    - datafiles
    - configuration
